on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      # - name: 'Testing Github action'
      #   run: pwd

      # - name: 'Testing Printing'
      #   run: echo Rahma

      # - name: 'Befor'
      #   run: ls

        
       - uses: actions/checkout@v3
          
      #  - name: 'After'
      #    run: ls
       - name: "Login to Docker hub"
         run: docker login --username rahmaelraw --password dckr_pat_OLwv55WYNGVH8bh18ndyLYCu4vM

