on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      # - name: 'Testing Github action'
      #   run: pwd

      # - name: 'Testing Printing'
      #   run: echo Rahma

      # - name: 'Befor'
      #   run: ls

        
       - uses: actions/checkout@v3
          
      #  - name: 'After'
      #    run: ls
       - name: Login to DockerHub
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

       - name: "Building docker image"
         run: docker run -t ${{ secrets.DOCKER_USERNAME }}/myimage .

       - name: "Pushing to Docker hub"
         run: docker push ${{ secrets.DOCKER_USERNAME }}/myimage